"""empty message

Revision ID: f9b1263d2635
Revises: 
Create Date: 2024-01-04 11:19:35.827406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b1263d2635'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('HotelId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('HotelName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('HotelId'),
    sa.UniqueConstraint('HotelName')
    )
    op.create_table('order_status',
    sa.Column('IdStatus', sa.Integer(), nullable=False),
    sa.Column('StatusName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('IdStatus'),
    sa.UniqueConstraint('StatusName')
    )
    op.create_table('order_types',
    sa.Column('IDTypeOrder', sa.Integer(), nullable=False),
    sa.Column('OrderTypeName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('IDTypeOrder'),
    sa.UniqueConstraint('OrderTypeName')
    )
    op.create_table('users',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(), nullable=False),
    sa.Column('Password', sa.String(), nullable=False),
    sa.Column('FullName', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Password'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('locations',
    sa.Column('LocationId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LocationType', sa.String(), nullable=False),
    sa.Column('LocationName', sa.String(), nullable=False),
    sa.Column('Floor', sa.Integer(), nullable=False),
    sa.Column('HotelId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['HotelId'], ['hotels.HotelId'], name='fk_location_hotel', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('LocationId')
    )
    op.create_table('orders',
    sa.Column('IdOrder', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Location', sa.Integer(), nullable=True),
    sa.Column('CreationDate', sa.DateTime(), nullable=True),
    sa.Column('EndDate', sa.DateTime(), nullable=True),
    sa.Column('OrderType', sa.Integer(), nullable=True),
    sa.Column('ImageData', sa.LargeBinary(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('Status', sa.Integer(), nullable=True),
    sa.Column('HotelId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], name='fk_orderType', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['HotelId'], ['hotels.HotelId'], name='fk_location_hotel', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Location'], ['locations.LocationId'], name='fk_location', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['OrderType'], ['order_types.IDTypeOrder'], name='fk_ordertype', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Status'], ['order_status.IdStatus'], name='fk_orderstatus', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('IdOrder')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('locations')
    op.drop_table('users')
    op.drop_table('order_types')
    op.drop_table('order_status')
    op.drop_table('hotels')
    # ### end Alembic commands ###
